---
- name: restart nginx
  service: name=nginx state=restarted

- name: validate nginx configuration
  command: nginx -t -c /etc/nginx/nginx.conf
  changed_when: false

- name: reload nginx
  service:
    name: nginx
    state: reloaded
    daemon_reload: true

- name: reload gunicorn
  service: name=hosewebview state=reloaded

- name: restart gunicorn
  service: name=hosewebview state=restarted
