# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.hostname = "raspi.test"
  config.vm.define "pidebian11"
  config.ssh.insert_key = false
  # config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network "private_network", ip: "192.168.60.10"
  config.vm.network "forwarded_port", guest: 1883, host: 9883
  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    # v.name = "pidebian11"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../ansible-playbooks/create-pi-user.yml"
  end
  
end
