---
- hosts: all
  become: yes


  vars_files:
    - vars/sensor-vars.yml
    - vars/mqtt-passwords.yml
    - vars/webview-vars.yml
    
  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600
      when: yes
  
  roles:
    - basic-pi-setup
    - basic-debian-setup
    - setup-weatherdata-collection
    - setup-mqtt-server
    - backup-sqlite-db
    - setup-hose-webview
